// <auto-generated />
using System;
using Gokart.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gokart.Data.Migrations
{
    [DbContext(typeof(GokartkolcsonzoContext))]
    partial class GokartkolcsonzoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GameStore.Entities.Berles", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Berles_hossza")
                        .HasColumnType("int");

                     b.Property<int>("Gokart_Id")
                        .HasColumnType("int");

                    b.Property<int>("Berlo_Id")
                        .HasColumnType("int");
                
                    b.Property<DateOnly>("KezdoDatum")
                        .HasColumnType("date");

                    b.HasKey("ID");

                    b.ToTable("Berles");
                });

            modelBuilder.Entity("GameStore.Entities.Berlo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Berlo_Neve")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Berlo");
                });

            modelBuilder.Entity("GameStore.Entities.Gokartok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Evjarat")
                        .HasColumnType("date");

                    b.Property<int>("Foglalt_e")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Gyarto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HajtasModja")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Hossz")
                        .HasColumnType("int");

                    b.Property<string>("MotorTipusa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NapiAr")
                        .HasColumnType("int");

                    b.Property<int>("Szelesseg")
                        .HasColumnType("int");

                    b.Property<int>("Teljesitmeny")
                        .HasColumnType("int");

                    b.Property<int>("Tengelytav")
                        .HasColumnType("int");

                    b.Property<string>("Tipus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Tomeg")
                        .HasColumnType("int");

                    b.Property<string>("ValtoTipusa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VazTipusa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Gokartok");
                });
#pragma warning restore 612, 618
        }
    }
}
